version: '3.8'
services:
  beancount:
    image: navaati/beancount
    restart: always
    ports:
      - "5099:5000"
    volumes:
      - ./ledger.beancount:/home/beancount/ledger_root/ledger.beancount
